[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "preswald-654793"  # Required: Unique identifier for your project
entrypoint = "community_gallery/my_dataset_example/hello.py"    # Required: Main script to run when executing preswald run

[branding]
name = "Preswald Project"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.manga_csv]
type = "csv"
path = "data/best-selling-manga.csv"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"